---
# tasks file for collectd
- apt: name=collectd
- file: src=/etc/collectd.conf dest=/etc/collectd/collectd.conf state=link force=yes
  notify: restart collectd
- copy: src={{ item }} dest=/usr/local/bin/ mode=775
  with_items:
    - dhcp-count
    - ipv6-count
    - ipv4-count
    - fastd-count
  notify: restart collectd
- template: src=collectd.conf.j2 dest=/etc/collectd.conf validate="collectd -C %s -t"
  notify: restart collectd
- service: name=collectd state=started enabled=yes
