#!/bin/sh


HOSTNAME="${COLLECTD_HOSTNAME:-localhost}"
INTERVAL="${COLLECTD_INTERVAL:-60}"

while sleep "$INTERVAL"; do
  VALUE=$(ip -4 n s dev br0 | grep 10\.40\..*REACHABLE | wc -l)
  echo "PUTVAL \"$HOSTNAME/neighbors-ipv4/gauge-count\" interval=$INTERVAL N:$VALUE"
done
