# Configure dnsmasq for DNS resolving
---
- apt: name=resolvconf
- apt: name=dnsmasq
- service: name=dnsmasq enabled=true
- template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf validate='dnsmasq --test -C %s'
  notify: restart dnsmasq
